apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-deployment
  labels:
    app: employee-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-deployment
  template:
    metadata:
      labels:
        app: employee-deployment
    spec:
      containers:
      - name: employee-deployment
        image: $image
        ports:
        - containerPort: 8083
